config/routes.rb
Rails.application.routes.draw do
  resources :entries

  root to: 'visitors#index'
  devise_for :users
  resources :entries, only: [:new, :edit, :create, :uptade, :destroy]

  resources :users do
    resources :entries, only: [:show]
  end
end

app/models/commetn.rb
class Commetn < ActiveRecord::Base
  validates :body, presence: true

  belongs_to :user
  belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :entries
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]


  def show
    @user = User.find(params[:user_id])
  end


  def new
    @entry = current_user.entries.build
  end


  def edit
  end


  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to user_entry_path(current_user,@entry), notice: 'Entry was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to current_user.entries.present? ? user_path(current_user) : "/", notice: 'Ently was successfully destroyed.' }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @entry = current_user.entries.last
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entries.html.haml
.container
  .row
    %h3 Entries
    .column
      %table
        %tbody
          - @user.entries.all.each do |entry|
            %tr
              %td= link_to '■'
              %td= link_to truncate(entry.content.lines.first, lingth: 10), entry

app/views/entries/_form.html.haml
= simple_form_for(@entry) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content

  .form-actions
    = f.button :submit

app/views/entries/_show.html.haml
.row
  .col-md-8
    %p#notice= notice
    %p
    %b Content
    = simple_format(h(@entry.content))
    %br
    - if @entry.user == current_user
      = link_to 'Edit', edit_entry_path(@entry)
      = link_to 'destroy', @entry, :method => 'delete'
  .col-md-4
    = render 'entries/entries'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Back', @entry

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.haml
= render 'show'

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li= link_to 'Home', root_path, class: 'navbar-brand'
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method => 'delete'
  %li= link_to '週報を書く', new_entry_path
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Academy0607'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Academy0607'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .row
        .col-md-4
          = render 'users/users'
        .col-md-8
          = yield

app/views/users/_users.html.haml
.container
  .row
    %h3 Users
    .column
      %table
        %tbody
          - User.all.each do |user|
            -if user.entries.present?
              %tr
                %td= link_to '(写)', user
                %td= link_to user.name, user

app/views/users/show.html.haml
= render 'entries/show'

app/views/visitors/index.html.haml
%h3 Welcome
%p
  = link_to 'Users:', users_path
  = User.count
  registered